server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/spring-security
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect 
        
        
 # DATABASE TABLES
 # 1-user -> username,password,enable;
   #data-in-user-table- admin,bcryptpassword,1
   #                    user,bcryptpassword,1
 # 2-role ->username authorities;
   # data-In-role-table- admin,ROLE_USER
   #                     user,ROLE_ADMIN
        